-- Demo data so a fresh database tells a story. Safe to delete for a production deployment.

INSERT OR IGNORE INTO members (id, name, email, role, timezone) VALUES
  (1, 'Naomi Achieng', 'naomi@cadence.example', 'team_lead', 'Africa/Nairobi'),
  (2, 'Brian Otieno',  'brian@cadence.example', 'sdr',       'Africa/Nairobi'),
  (3, 'Faith Wanjiru', 'faith@cadence.example', 'sdr',       'Africa/Nairobi'),
  (4, 'Pedro Alves',   'pedro@cadence.example', 'developer', 'America/Sao_Paulo');

INSERT OR IGNORE INTO leads (id, company, website, contact_name, contact_title, email, phone, industry, country, employees, source, stage, owner_id, score, notes, created_at, updated_at) VALUES
  (1,  'Harbor Point Dental',        'https://harborpointdental.com', 'Dr. Elena Ruiz',   'Owner',                'elena@harborpointdental.com', '+1 (206) 555-0142', 'Healthcare',        'United States', 14,  'linkedin', 'qualified',    2, 85, 'Two locations, opening a third in Q1. Interested in appointment-recovery automation.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-21 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-1 days')),
  (2,  'Summit Ridge Roofing',       'https://summitridgeroofing.com', 'Mark Delaney',     'General Manager',      'mark@summitridgeroofing.com', '+1 (303) 555-0177', 'Construction',      'United States', 42,  'webhook',  'contacted',    2, 70, 'Replied to the second email. Wants a call after the storm season.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-14 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-2 days')),
  (3,  'Lakeside Family Law',        NULL,                              'Priya Natarajan',  'Managing Partner',     'priya@lakesidefamilylaw.com', NULL,                NULL,                'United States', 9,   'manual',   'researching',  3, 45, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-6 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-6 hours')),
  (4,  'Northwind Logistics Ltd',    'https://northwindlogistics.co.uk', 'James Whitfield', 'Operations Director',  'j.whitfield@northwindlogistics.co.uk', '+44 20 7946 0958', 'Logistics', 'United Kingdom', 180, 'linkedin', 'validated',   3, 65, 'Fleet of 60. Pain point: manual proof-of-delivery reconciliation.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-9 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-1 days')),
  (5,  'Verde Contabilidade',        'https://verdecontabilidade.com.br', 'Camila Duarte', 'Sócia',               'camila@verdecontabilidade.com.br', '11987654321',  'Accounting & tax',  'Brazil',        23,  'manual',   'validated',    2, 60, 'Portuguese-speaking contact. Best reached mornings (BRT).', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-8 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-3 days')),
  (6,  'Bluebird Marketing Studio',  NULL,                              'Tasha Greene',     'Founder',              'tasha@bluebirdstudio.co',      NULL,                NULL,                NULL,            6,   'webhook',  'new',          NULL, 30, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-2 hours'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-2 hours')),
  (7,  'Kestrel Capital Partners',   'https://kestrelcap.com',          'Owen Blackwood',   'Managing Director',    'oblackwood@kestrelcap.com',    '+1 (212) 555-0113', 'Financial services','United States', 35,  'linkedin', 'disqualified', 3, 15, 'Compliance requires on-prem only. Revisit in 12 months.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-12 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-4 days')),
  (8,  'Mombasa Fresh Produce Co.',  'https://mombasafresh.co.ke',      'Amina Hassan',     'CEO',                  'amina@mombasafresh.co.ke',     '+254 722 000111',   NULL,                'Kenya',         55,  'manual',   'researching',  2, 50, 'Referral from Naomi. Exports to the EU; needs supplier-onboarding paperwork automated.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-3 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-5 hours')),
  (9,  'Pinecrest Physical Therapy', NULL,                              'Dr. Samuel Osei',  'Owner',                'sam@pinecrestpt.com',          '+1 (404) 555-0199', NULL,                'United States', 11,  'linkedin', 'new',          3, 35, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-1 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-1 days')),
  (10, 'Ironwood Fabrication',       'https://ironwoodfab.com',         'Dale Kowalski',    'Plant Manager',        'dale@ironwoodfab.com',         '+1 (614) 555-0128', 'Manufacturing',     'United States', 120, 'manual',   'contacted',    3, 68, 'Left voicemail twice; email opened 3x.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-10 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-1 days')),
  (11, 'Casa Bonita Hospitality',    'https://casabonitahotels.mx',     'Lucía Fernández',  'Directora General',    'lucia@casabonitahotels.mx',    '+52 55 1234 5678',  'Hospitality',       'Mexico',        260, 'linkedin', 'validated',    2, 62, 'Three boutique hotels. Interested in guest-message triage.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-7 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-2 days')),
  (12, 'Greenfield Academy',         'https://greenfieldacademy.org',   'Robert Achterberg','Head of School',       'rachterberg@greenfieldacademy.org', NULL,           'Education',         'United States', 48,  'manual',   'researching',  3, 42, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-4 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-1 days')),
  (13, 'Atlas HVAC & Electric',      NULL,                              'Tony Marchetti',   'Owner',                'tony@atlashvacelectric.com',   '9735550102',        NULL,                NULL,            17,  'webhook',  'new',          NULL, 25, 'Came in through the website form.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-5 hours'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-5 hours')),
  (14, 'Solace Wealth Advisors',     'https://solacewealth.com',        'Grace Kim',        'Partner',              'gkim@solacewealth.com',        '+1 (415) 555-0161', 'Financial services','United States', 28,  'linkedin', 'qualified',    3, 88, 'Signed the pilot proposal. Kickoff next Tuesday.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-18 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-3 days')),
  (15, 'Riverbend Veterinary Clinic','https://riverbendvet.com',        'Dr. Hannah Lowe',  'Practice Owner',       'hannah@riverbendvet.com',      '+1 (512) 555-0134', 'Healthcare',        'United States', 19,  'manual',   'contacted',    2, 72, 'Demo booked for Thursday 10:00 CT.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-11 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-8 hours')),
  (16, 'Nairobi Tech Labs',          'https://nairobitechlabs.co.ke',   'Kevin Mwangi',     'CTO',                  'kevin@nairobitechlabs.co.ke',  '+254 711 222333',   'Software',          'Kenya',         40,  'linkedin', 'researching',  2, 48, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-2 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-3 hours')),
  (17, 'Copperline Trucking',        NULL,                              'Denise Carter',    'Dispatch Manager',     'denise@copperlinetrucking.com', '+1 (816) 555-0147','Logistics',         'United States', 75,  'manual',   'new',          2, 40, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-1 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-1 days')),
  (18, 'Oakhurst Senior Living',     'https://oakhurstliving.com',      'Miriam Feldman',   'Executive Director',   'mfeldman@oakhurstliving.com',  '+1 (503) 555-0188', 'Healthcare',        'United States', 210, 'linkedin', 'disqualified', 2, 20, 'Chose a competitor last quarter.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-16 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-9 days'));

INSERT OR IGNORE INTO lead_stage_events (lead_id, from_stage, to_stage, member_id, reason, created_at) VALUES
  (1, NULL, 'new', 2, 'Created from linkedin', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-21 days')),
  (1, 'new', 'researching', 2, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-20 days')),
  (1, 'researching', 'validated', 2, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-18 days')),
  (1, 'validated', 'contacted', 2, 'Intro email sent', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-15 days')),
  (1, 'contacted', 'qualified', 2, 'Discovery call done, budget confirmed', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-1 days')),
  (2, NULL, 'new', NULL, 'Created from webhook', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-14 days')),
  (2, 'new', 'researching', 2, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-13 days')),
  (2, 'researching', 'validated', 2, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-11 days')),
  (2, 'validated', 'contacted', 2, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-2 days')),
  (3, NULL, 'new', 3, 'Created from manual', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-6 days')),
  (3, 'new', 'researching', 3, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-6 hours')),
  (4, NULL, 'new', 3, 'Created from linkedin', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-9 days')),
  (4, 'new', 'researching', 3, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-8 days')),
  (4, 'researching', 'validated', 3, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-1 days')),
  (5, NULL, 'new', 2, 'Created from manual', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-8 days')),
  (5, 'new', 'researching', 2, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-7 days')),
  (5, 'researching', 'validated', 2, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-3 days')),
  (6, NULL, 'new', NULL, 'Created from webhook', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-2 hours')),
  (7, NULL, 'new', 3, 'Created from linkedin', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-12 days')),
  (7, 'new', 'researching', 3, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-11 days')),
  (7, 'researching', 'disqualified', 3, 'On-prem only policy', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-4 days')),
  (8, NULL, 'new', 2, 'Created from manual', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-3 days')),
  (8, 'new', 'researching', 2, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-5 hours')),
  (9, NULL, 'new', 3, 'Created from linkedin', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-1 days')),
  (10, NULL, 'new', 3, 'Created from manual', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-10 days')),
  (10, 'new', 'researching', 3, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-9 days')),
  (10, 'researching', 'validated', 3, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-7 days')),
  (10, 'validated', 'contacted', 3, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-1 days')),
  (11, NULL, 'new', 2, 'Created from linkedin', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-7 days')),
  (11, 'new', 'researching', 2, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-6 days')),
  (11, 'researching', 'validated', 2, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-2 days')),
  (12, NULL, 'new', 3, 'Created from manual', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-4 days')),
  (12, 'new', 'researching', 3, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-1 days')),
  (13, NULL, 'new', NULL, 'Created from webhook', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-5 hours')),
  (14, NULL, 'new', 3, 'Created from linkedin', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-18 days')),
  (14, 'new', 'researching', 3, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-17 days')),
  (14, 'researching', 'validated', 3, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-15 days')),
  (14, 'validated', 'contacted', 3, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-12 days')),
  (14, 'contacted', 'qualified', 3, 'Pilot signed', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-3 days')),
  (15, NULL, 'new', 2, 'Created from manual', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-11 days')),
  (15, 'new', 'researching', 2, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-10 days')),
  (15, 'researching', 'validated', 2, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-9 days')),
  (15, 'validated', 'contacted', 2, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-8 hours')),
  (16, NULL, 'new', 2, 'Created from linkedin', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-2 days')),
  (16, 'new', 'researching', 2, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-3 hours')),
  (17, NULL, 'new', 2, 'Created from manual', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-1 days')),
  (18, NULL, 'new', 2, 'Created from linkedin', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-16 days')),
  (18, 'new', 'researching', 2, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-15 days')),
  (18, 'researching', 'validated', 2, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-14 days')),
  (18, 'validated', 'contacted', 2, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-12 days')),
  (18, 'contacted', 'disqualified', 2, 'Chose a competitor', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-9 days'));

INSERT OR IGNORE INTO enrichment_suggestions (id, lead_id, field, suggested_value, current_value, source, confidence, rationale, status, reviewed_by, reviewed_at, created_at) VALUES
  (1, 3,  'website',  'https://lakesidefamilylaw.com', NULL, 'heuristic', 0.85, 'Derived from the email domain lakesidefamilylaw.com; not a free-mail provider.', 'pending', NULL, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-6 hours')),
  (2, 3,  'industry', 'Legal services', NULL, 'heuristic', 0.6, 'Company name contains "law".', 'pending', NULL, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-6 hours')),
  (3, 8,  'industry', 'Agriculture & food export', NULL, 'llm', 0.72, 'Company name and .co.ke domain plus notes about EU produce exports.', 'pending', NULL, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-5 hours')),
  (4, 13, 'website',  'https://atlashvacelectric.com', NULL, 'heuristic', 0.85, 'Derived from the email domain atlashvacelectric.com; not a free-mail provider.', 'pending', NULL, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-5 hours')),
  (5, 13, 'industry', 'Construction', NULL, 'heuristic', 0.6, 'Company name contains "hvac".', 'pending', NULL, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-5 hours')),
  (6, 13, 'phone',    '+1 (973) 555-0102', '9735550102', 'heuristic', 0.7, 'Normalised a 10-digit number to the North American format; confirm the country.', 'pending', NULL, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-5 hours')),
  (7, 6,  'website',  'https://bluebirdstudio.co', NULL, 'heuristic', 0.85, 'Derived from the email domain bluebirdstudio.co; not a free-mail provider.', 'pending', NULL, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-2 hours')),
  (8, 6,  'industry', 'Marketing agency', NULL, 'heuristic', 0.6, 'Company name contains "marketing".', 'pending', NULL, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-2 hours')),
  (9, 4,  'industry', 'Logistics', NULL, 'heuristic', 0.6, 'Company name contains "logistics".', 'accepted', 3, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-8 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-8 days')),
  (10, 5, 'phone',    '+55 11 98765-4321', '11987654321', 'heuristic', 0.7, 'Looks like a Brazilian mobile number; normalised to +55 format.', 'pending', NULL, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-3 days')),
  (11, 11, 'employees', '260', NULL, 'llm', 0.55, 'Three boutique hotels typically employ 80-100 staff each.', 'accepted', 2, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-6 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-6 days')),
  (12, 7, 'country',  'United States', NULL, 'llm', 0.5, 'Managing director title and .com domain; weak signal.', 'rejected', 3, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-11 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-11 days')),
  (13, 12, 'country', 'United States', NULL, 'llm', 0.6, '.org domain and "Head of School" title are common in US independent schools.', 'accepted', 3, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-3 days'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-4 days'));

INSERT OR IGNORE INTO activities (lead_id, member_id, kind, summary, outcome, occurred_at) VALUES
  (1, 2, 'call',     'Discovery call with Dr. Ruiz', 'Budget confirmed for Q1; wants a proposal by Friday.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-1 days')),
  (1, 2, 'email',    'Sent the case study on appointment recovery', 'Opened twice.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-5 days')),
  (2, 2, 'email',    'Second follow-up after storm season note', 'Replied: call after the 20th.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-2 days')),
  (2, 2, 'email',    'Intro email with the roofing playbook', NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-11 days')),
  (10, 3, 'call',    'Voicemail for Dale', 'No answer; email opened 3x.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-1 days')),
  (10, 3, 'linkedin','Connection request accepted', NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-6 days')),
  (14, 3, 'meeting', 'Pilot kickoff planning with Grace', 'Kickoff Tuesday 14:00 PT.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-3 days')),
  (15, 2, 'call',    'Booked demo with Dr. Lowe', 'Thursday 10:00 CT.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-8 hours')),
  (4, 3, 'note',     'Reviewed Companies House filing: 180 employees, revenue up 12%', NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-1 days')),
  (8, 2, 'note',     'Naomi referral; Amina prefers WhatsApp', NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-5 hours')),
  (11, 2, 'email',   'Sent Spanish-language intro', 'Delivered.', strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-2 days')),
  (16, 2, 'linkedin','Commented on Kevin''s post about supplier onboarding', NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-3 hours'));

INSERT OR IGNORE INTO standups (member_id, day, yesterday, today, metric, blockers, help_needed) VALUES
  (1, date('now'), 'Reviewed the pilot proposal for Solace Wealth; coached Faith on validation criteria.', 'Send management the weekly funnel; unblock the D1 credentials for Pedro.', '2 qualified leads this week (target 3).', '', ''),
  (2, date('now'), 'Discovery call with Harbor Point Dental (qualified). Booked the Riverbend Vet demo.', 'Clear the 4 pending AI suggestions on my leads; 15 outreach touches.', '15 touches, 2 replies.', 'Summit Ridge asked for a case study we do not have for roofing.', 'Naomi: can we reuse the HVAC case study with a roofing intro?'),
  (3, date('now'), 'Validated Northwind Logistics after the Companies House check. Voicemail for Ironwood.', 'Research Lakeside Family Law and Greenfield Academy; second touch on Ironwood.', '3 leads validated (target 4).', '', ''),
  (4, date('now'), 'Shipped the webhook signature check and the suggestion review flow.', 'Daily report generator; D1 batch endpoint in the Worker.', 'Report generated from real stand-up data by end of day.', 'Need the Cloudflare account API token to run wrangler d1 migrations apply.', 'Naomi: Cloudflare token with D1 edit scope.'),
  (1, date('now', '-1 day'), 'Weekly pipeline review with management.', 'Review Solace proposal; 1:1 with Brian.', '3 qualified this week.', '', ''),
  (2, date('now', '-1 day'), '12 touches; Summit Ridge replied.', 'Discovery call with Harbor Point Dental.', '15 touches.', '', ''),
  (3, date('now', '-1 day'), 'Researched Northwind Logistics.', 'Validate Northwind; start Lakeside research.', '4 validations.', 'Companies House site was down for an hour.', ''),
  (4, date('now', '-1 day'), 'Migrations 0001 and 0002 running on SQLite and D1.', 'Webhook endpoint with HMAC verification.', 'Rejected signatures logged with a reason.', '', '');

INSERT OR IGNORE INTO webhook_deliveries (source, event, payload, signature_valid, status, detail, lead_id, received_at) VALUES
  ('website-form', 'lead.created', '{"company":"Atlas HVAC & Electric","contact_name":"Tony Marchetti","email":"tony@atlashvacelectric.com","phone":"9735550102"}', 1, 'accepted', 'Created lead #13', 13, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-5 hours')),
  ('website-form', 'lead.created', '{"company":"Bluebird Marketing Studio","contact_name":"Tasha Greene","email":"tasha@bluebirdstudio.co"}', 1, 'accepted', 'Created lead #6', 6, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-2 hours')),
  ('unknown',      'lead.created', '{"company":"Totally Legit Leads","email":"spam@example.com"}', 0, 'rejected', 'Signature mismatch', NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-1 hours')),
  ('website-form', 'lead.created', '{"company":"Summit Ridge Roofing","contact_name":"Mark Delaney","email":"mark@summitridgeroofing.com"}', 1, 'accepted', 'Created lead #2', 2, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-14 days'));
